endlessride/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from shop.forms import CustomAuthenticationForm
from . import views
from django.conf import settings
from django.conf.urls.static import static
from shop.views import agregar_producto_carrito,agregar_producto_carrito_otro , eliminar_producto_carrito, panel_pedidos, procesar_pedido, restar_producto_carrito, limpiar_carrito, tienda, carrito, comprar_producto, mis_pedidos
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('', views.inicio, name="inicio"),
    path('tienda', tienda, name='tienda'),
    path('carrito', carrito, name='carrito'),
    path('mis_pedidos/', mis_pedidos, name='mis_pedidos'),
    path('comprar/<int:producto_id>/', comprar_producto, name='comprar_producto'),
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(authentication_form=CustomAuthenticationForm), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('agregar/<int:producto_id>/', agregar_producto_carrito, name="agregar"),
    path('agregar_otro/<int:producto_id>/', agregar_producto_carrito_otro, name="agregar_otro"),
    path('eliminar/<int:producto_id>/', eliminar_producto_carrito, name="eliminar"),
    path('restas/<int:producto_id>/', restar_producto_carrito, name="restar"),
    path('limpiar/', limpiar_carrito, name="limpiar"),
    path('procesar_pedido/', procesar_pedido, name='procesar_pedido'),
    path('shop/pedidos/', panel_pedidos, name='panel_pedidos'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:producto_id>', views.detalle, name='detalle'),
    path('stickers', views.stickers, name='stickers'),
    path('llantas', views.llantas, name='llantas'),
    path('accesorios', views.accesorios, name='accesorios'),
    path('contacto', views.contacto, name='contacto'),
    path('tienda', views.tienda, name='tienda'),
    path('agregar-producto', views.agregar_producto, name='agregar_producto'),
    path('modificar-producto/<id>/', views.modificar_producto, name='modificar_producto'),
    path('eliminar-producto/<id>/', views.eliminar_producto, name='eliminar_producto'),
    path('registro', views.registro, name='registro'),
]

shop/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=255)
    imagen = models.ImageField(upload_to="categorias", null=True)
    
    def __str__(self):
        return self.nombre
    
class Producto (models.Model):
    nombre = models.CharField(max_length=255)
    stock = models.IntegerField()
    precio = models.IntegerField(default=0)
    descripcion = models.TextField(null=True)
    categoria = models.ForeignKey(Categoria, on_delete= models.CASCADE)
    creado_en = models.DateTimeField(default=timezone.now)
    imagen = models.ImageField(upload_to="productos", null=True)
    
    def __str__(self):
        return self.nombre


class Carro(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)
    comprado = models.BooleanField(default=False)
    fecha_compra = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.usuario.username} - {self.producto.nombre}"


class Contacto (models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    mensaje = models.TextField()
    
    
    
    def __str__(self):
        return self.nombre

class Pedido(models.Model):
    ESTADO_CHOICES = [
        ('PENDIENTE', 'Pendiente'),
        ('DESPACHO', 'En Despacho'),
        ('TRANSITO', 'En Tránsito'),
        ('ENTREGADO', 'Entregado'),
    ]

    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    creado_en = models.DateTimeField(auto_now_add=True)
    estado = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='PENDIENTE')

    def __str__(self):
        return f'Pedido #{self.id} - {self.usuario.username}'

class PedidoItem(models.Model):
    pedido = models.ForeignKey(Pedido, related_name='items', on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    subtotal = models.DecimalField(max_digits=10, decimal_places=2)
    
    def __str__(self):
        return f'{self.cantidad} de {self.producto.nombre}'

shop/forms.py
from django import forms
from . import models
from django.forms import ModelForm
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class ProductoForm(ModelForm):
    class Meta:
        model = models.Producto
        fields = ['nombre', 'stock', 'precio', 'categoria','descripcion' , 'imagen',]
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'stock': forms.NumberInput(attrs={'class': 'form-control'}),
            'precio': forms.NumberInput(attrs={'class': 'form-control'}),
            'categoria': forms.Select(attrs={'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control'}),
            'imagen': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }
        
class ContactoForm(ModelForm):
    class Meta:
        model = models.Contacto
        fields = ['nombre', 'correo', 'mensaje',]
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'correo': forms.TextInput(attrs={'class': 'form-control'}),
            'mensaje': forms.Textarea(attrs={'class': 'form-control'}),
        }
        
class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        help_text=None
    )
    password1 = forms.CharField(
        label="Contraseña",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )
    password2 = forms.CharField(
        label="Confirme Contraseña",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'})
        }

shop/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from .forms import ContactoForm, ProductoForm, CustomUserCreationForm
from .models import Producto
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, permission_required


# Create your views here.


@permission_required('shop.view_producto')
def index (request):
    productos = Producto.objects.all()
    page = request.GET.get('page', 1)
    
    try:
        paginator = Paginator(productos, 10)
        productos = paginator.page(page)
    except:
        raise Http404
    
    data = {
        'entity': productos,
        'paginator': paginator,
        
    }
    return render(
        request,
        'index.html',
        context={
            'productos': productos,
            'paginator': paginator}
    )



def detalle(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    producto = Producto.objects.get(id=producto_id)
        
    return render(
        request, 
        'detalle.html', 
        context= {'producto': producto})
    

    
def stickers(request):
    productos = Producto.objects.filter(categoria_id=1)
    return render(request, 'stickers.html', {'productos': productos})

def llantas(request):
    productos = Producto.objects.filter(categoria_id=2)
    return render(request, 'llantas.html', {'productos': productos})

def accesorios(request):
    productos = Producto.objects.filter(categoria_id=3)
    return render(request, 'accesorios.html', {'productos': productos})

def contacto(request):
    if request.method == 'POST':
        form = ContactoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/shop/contacto')  
    else:
        form = ContactoForm()

    data = {
        'contacto_form': form
    }
    return render(request, 'contacto.html', data)

def tienda(request):

    return render(request, 'tienda.html')




@permission_required('shop.add_producto')
def agregar_producto (request):
    data= {
        'form': ProductoForm()
    }
    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, files=request.FILES)
        if formulario.is_valid():
           formulario.save()
           messages.success(request, "Agregado Correctamente")
        else:
            data["form"] = formulario
    
    return render(request,'producto/agregar.html', data)



@permission_required('shop.change_producto')
def modificar_producto(request, id):
    producto = get_object_or_404(Producto, id=id)
    data = {
        'form' : ProductoForm(instance=producto)
    }
    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, instance=producto, files=request.FILES)
        if formulario.is_valid():
           formulario.save()
           messages.success(request, "Modificado Correctamente")
           return HttpResponseRedirect('/shop')
        else:
            data["form"] = formulario
    
    return render(request, 'producto/modificar.html',data)



@permission_required('shop.delete_producto')
def eliminar_producto(request, id):
    producto = get_object_or_404(Producto, id=id)
    producto.delete()
    messages.success(request, "Eliminado Correctamente")
    return HttpResponseRedirect('/shop')
    
    
def registro (request):
    data = {
        'form': CustomUserCreationForm()
    }
    if request.method == 'POST':
        formulario = CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username= formulario.cleaned_data["username"], password=formulario.cleaned_data["password1"])
            login(request, user)
            messages.success(request, "Registrado Correctamente")
            return redirect(to="inicio")
        data['form'] = formulario
    return render(request, 'registration/registro.html', data)

shop/templates/accesorios.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <div class="mt-5 text-center">
        <h1>ACCESORIOS</h1>
        <hr class="my-4">
    </div>
    
    {% load humanize %}
    {{ value|intcomma }}
    <div class="container mt-4">
        <div class="row">
            {% for producto in productos %}
            <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-4 ">
                <div class="card h-100 border-0" >
                    {% if producto.imagen %}
                    <a href="{% url 'shop:detalle' producto.id %}"><img src="{{ producto.imagen.url }}" class="card-img-top img-fluid d-block" alt="{{ producto.nombre }}"></a>
                    {% endif %}
                    <div class="card-body">
                        <h4 class="card-title text-center">{{ producto.nombre }}</h4>
                        <p class="card-text text-center">${{ producto.precio|intcomma }}</p>
                        <div class="text-center mb-5">
                            <a href="{% url 'shop:detalle' producto.id %}" class="btn btn-outline-primary">Ver Producto</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

shop/templates/contacto.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}

    <br>
    <div class="mt-5 text-center">
        <h1>Contacto</h1>
    </div>
    
    <form 
    novalidate
    action="{% url 'shop:contacto' %}"
    method='post'>
    {% csrf_token %}
    {{ contacto_form }}

    <button type="submit" id="btnEnviar" class="btn btn-outline-primary mb-5">Enviar</button>
</form>
    </form>
    
{% endblock %}

shop/templates/detalle.html
{% extends 'base.html' %}

{% block content %}


<div class="mt-5">
    <br>
</div>
<div class="card mb-3 mt-5 mb-5 border-0">
    <div class="row g-0 mb-5">
        <div class="col-md-4">
            <img src="{{ producto.imagen.url }}" alt="{{ producto.nombre }}" style="max-width: 100%; height: auto;">
        </div>
        <div class="container col-md-8 ">
            <div class="card-body">
                <h1 class="card-title text-center">{{ producto.nombre }}</h1>
                <p class="card-text text-center"><small class="text-body-secondary">Categoria: {{ producto.categoria }}</small></p>
                <hr class="my-4">
                <br>
                
                <p class="card-text">{{ producto.descripcion }}</p>
                <div class="row mt-5">
                    <h2 class="card-text  col-6">${{ producto.precio }}</h2>
                    <button type="button" class="btn btn-outline-primary col-6">Agregar Al Carrito</button>
                </div>
            </div>
        </div>
    </div>
</div>





{% endblock %}

shop/templates/index.html
{% extends 'base.html' %}
{% block js %}
    <script>
        function eliminarProducto(id){
            Swal.fire({
                "title": "Estas seguro que deseas eliminar?",
                "icon": "warning",
                "showCancelButton": true,
                "confirmButtonText": "Eliminar",
                "reverseButtons": true,
                "confirmButtonColor": "red"
            })
            .then(function(result){
                if(result.isConfirmed){
                    window.location.href = "/shop/eliminar-producto/"+id+"/"
                }
            })
        }
    </script>
{% endblock %}
{% block content %}

<br>
<h1 class="mt-5">Productos</h1>
<a href="{% url "shop:agregar_producto" %}"class="btn btn-outline-primary">Nuevo Producto</a>
<a href="{% url 'shop:panel_pedidos' %}" class="btn btn-outline-primary">Ir al Panel de Pedidos</a>


<table class="table">
    <thead>
        <tr>
            <th>Imagen</th>
            <th>Nombre</th>
            <th>Stock</th>
            <th>Precio</th>
            <th>Categoria</th>
            <th>Creacion</th>
            <th></th>

            
        </tr>
    </thead>

    <tbody>
        {% for producto in productos %}
        <tr>
            <td><img src="{{ producto.imagen.url }}" alt="{{ producto.nombre }}" style="max-width: 100px; height: auto;"></td>
            <td><a href="{% url 'shop:modificar_producto' producto.id %}">{{ producto.nombre }}</a></td>
            <td>{{ producto.stock }}</td>
            <td>{{ producto.precio }}</td>
            <td>{{ producto.categoria }}</td>
            <td>{{ producto.creado_en }}</td>
            <td><a href="#" onclick="eliminarProducto({{ producto.id }})" class=" btn btn-close "></a></td>

            
            
        </tr>
        {% endfor %}
    </tbody>

</table>
    {% include 'paginator.html' %}

{% endblock %}

shop/templates/llantas.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <div class="mt-5 text-center">
        <h1>LLANTAS</h1>
        <hr class="my-4">
    </div>
    
    {% load humanize %}
    {{ value|intcomma }}
    <div class="container mt-4">
        <div class="row">
            {% for producto in productos %}
            <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-4 ">
                <div class="card h-100 border-0" >
                    {% if producto.imagen %}
                    <a href="{% url 'shop:detalle' producto.id %}"><img src="{{ producto.imagen.url }}" class="card-img-top img-fluid d-block" alt="{{ producto.nombre }}"></a>
                    {% endif %}
                    <div class="card-body">
                        <h4 class="card-title text-center">{{ producto.nombre }}</h4>
                        <p class="card-text text-center">${{ producto.precio|intcomma }} c/u</p>
                        <div class="text-center mb-5">
                            <a href="{% url 'shop:detalle' producto.id %}" class="btn btn-outline-primary">Ver Producto</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

shop/templates/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if productos.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ productos.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != productos.number and paginator.num_pages > 7 %} 
                {% if productos.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ productos.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == productos.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == productos.number %}
            <li class="page-item {% if page == productos.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if productos.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ productos.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if productos.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ productos.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if productos.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ productos.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}

shop/templates/panel_pedidos.html
{% extends 'base.html' %}

{% block content %}

<div style="padding: 100px;">
    <div class="container">
        <h2 class="text-center">Panel de Pedidos</h2>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Fecha</th>
                    <th scope="col">Usuario</th>
                    <th scope="col">Cantidad de Productos</th>
                    <th scope="col">Total</th>
                    <th scope="col">Estado</th>
                </tr>
            </thead>
            <tbody>
                {% for pedido in pedidos %}
                    <tr>
                        <td>{{ pedido.id }}</td>
                        <td>{{ pedido.creado_en }}</td>
                        <td>{{ pedido.usuario.username }}</td>
                        <td>{{ pedido.items.count }}</td>  {# Contar la cantidad de productos en el pedido #}
                        <td>${{ pedido.total }}</td>  {# Suponiendo que tienes un campo total en tu modelo Pedido #}
                        <td>
                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="pedido_id" value="{{ pedido.id }}">
                                <select name="nuevo_estado" class="form-control" onchange="this.form.submit()">
                                    <option value="PENDIENTE" {% if pedido.estado == 'PENDIENTE' %} selected {% endif %}>Pendiente</option>
                                    <option value="DESPACHO" {% if pedido.estado == 'DESPACHO' %} selected {% endif %}>En Despacho</option>
                                    <option value="TRANSITO" {% if pedido.estado == 'TRANSITO' %} selected {% endif %}>En Tránsito</option>
                                    <option value="ENTREGADO" {% if pedido.estado == 'ENTREGADO' %} selected {% endif %}>Entregado</option>
                                </select>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

shop/templates/stickers.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <div class="mt-5 text-center">
        <h1>STICKERS</h1>
        <hr class="my-4">
    </div>
    
    {% load humanize %}
    {{ value|intcomma }}
    <div class="container mt-4">
        <div class="row">
            {% for producto in productos %}
            <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-4 ">
                <div class="card h-100 border-0" >
                    {% if producto.imagen %}
                    <a href="{% url 'shop:detalle' producto.id %}"><img src="{{ producto.imagen.url }}" class="card-img-top img-fluid d-block" alt="{{ producto.nombre }}"></a>
                    {% endif %}
                    <div class="card-body">
                        <h4 class="card-title text-center">{{ producto.nombre }}</h4>
                        <p class="card-text text-center">${{ producto.precio|intcomma }}</p>
                        <div class="text-center mb-5">
                            <a href="{% url 'shop:detalle' producto.id %}" class="btn btn-outline-primary">Ver Producto</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

shop/templates/tienda.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <br>
    <div class="mt-5 text-center">
        <h1>Tienda</h1>
        <hr class="my-4">
    </div>
    
    <div class=" mt-5">
        <div class="row mt-5">
            <div class="col-12 col-sm-6 col-md-4 col-lg-4 mb-4 ">
                <div class="card h-100 border-0" >
                    <a href="{% url "shop:stickers" %}" ><img src="{% static 'img/categoriasticekr.png' %} " class="card-img-top img-fluid d-block" alt=""></a>
                    <div class="card-body">
                        <h2 class="card-title text-center mt-3">Stickers</h2>
                        <div class="text-center mb-5">
                            <a href="{% url "shop:stickers" %}" class="btn btn-outline-primary mt-2">Ver Productos</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-6 col-md-4 col-lg-4 mb-4 ">
                <div class="card h-100 border-0" >
                    <a href="{% url "shop:llantas" %}" ><img src="{% static 'img/categoriallanta.png' %} " class="card-img-top img-fluid d-block" alt=""></a>
                    <div class="card-body">
                        <h2 class="card-title text-center mt-3">Llantas</h2>
                        <div class="text-center mb-5">
                            <a href="{% url "shop:llantas" %}" class="btn btn-outline-primary mt-2">Ver Productos</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-6 col-md-4 col-lg-4 mb-4 ">
                <div class="card h-100 border-0" >
                    <a href="{% url "shop:accesorios" %}" ><img src="{% static 'img/categoriaescape.png' %} " class="card-img-top img-fluid d-block" alt=""></a>
                    <div class="card-body">
                        <h2 class="card-title text-center mt-3">Accesorios</h2>
                        <div class="text-center mb-5">
                            <a href="{% url "shop:accesorios" %}" class="btn btn-outline-primary mt-2">Ver Productos</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}