endlessride/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from shop.forms import CustomAuthenticationForm
from . import views
from django.conf import settings
from django.conf.urls.static import static
from shop.views import agregar_producto_carrito,agregar_producto_carrito_otro , eliminar_producto_carrito, panel_pedidos, procesar_pedido, restar_producto_carrito, limpiar_carrito, tienda, carrito, comprar_producto, mis_pedidos
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('', views.inicio, name="inicio"),
    path('tienda', tienda, name='tienda'),
    path('carrito', carrito, name='carrito'),
    path('mis_pedidos/', mis_pedidos, name='mis_pedidos'),
    path('comprar/<int:producto_id>/', comprar_producto, name='comprar_producto'),
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(authentication_form=CustomAuthenticationForm), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('agregar/<int:producto_id>/', agregar_producto_carrito, name="agregar"),
    path('agregar_otro/<int:producto_id>/', agregar_producto_carrito_otro, name="agregar_otro"),
    path('eliminar/<int:producto_id>/', eliminar_producto_carrito, name="eliminar"),
    path('restas/<int:producto_id>/', restar_producto_carrito, name="restar"),
    path('limpiar/', limpiar_carrito, name="limpiar"),
    path('procesar_pedido/', procesar_pedido, name='procesar_pedido'),
    path('shop/pedidos/', panel_pedidos, name='panel_pedidos'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:producto_id>', views.detalle, name='detalle'),
    path('stickers', views.stickers, name='stickers'),
    path('llantas', views.llantas, name='llantas'),
    path('accesorios', views.accesorios, name='accesorios'),
    path('contacto', views.contacto, name='contacto'),
    path('tienda', views.tienda, name='tienda'),
    path('agregar-producto', views.agregar_producto, name='agregar_producto'),
    path('modificar-producto/<id>/', views.modificar_producto, name='modificar_producto'),
    path('eliminar-producto/<id>/', views.eliminar_producto, name='eliminar_producto'),
    path('registro', views.registro, name='registro'),
]

templates/base.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
    <nav class="navbar bg-body-tertiary fixed-top bg-dark border-bottom border-body" data-bs-theme="dark"">
        <div class="container-fluid">
          <a class="navbar-brand ms-2" href="{% url "inicio" %}">ENDLESSRIDE</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header">
              <h5 class="offcanvas-title" id="offcanvasNavbarLabel">ENDLESSRIDE</h5>
              <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
              <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <li class="nav-item">
                  <a class="nav-link active text-white" aria-current="page" href="{% url "inicio" %}">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url "shop:tienda" %}">Tienda</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url "shop:contacto" %}">Contacto</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url "shop:carrito" %}">Carrito</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url "shop:mis_pedidos" %}">Mis pedidos</a>
                </li>
                {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link text-white" href="#" onclick="document.getElementById('logout-form').submit(); return false;">Cerrar Sesion</a>
                  </li>
                  <form id="logout-form" method="post" action="{% url 'logout' %}" style="display: none;">
                    {% csrf_token %}
                  </form>
                {% else %}
                  <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'login' %}">Iniciar Sesion</a>
                  </li>            
                {% endif %}
                {% if perms.shop.view_producto %}
                  <li class="nav-item">
                    <a href="{% url 'shop:index' %}" class="nav-link text-white">Administración</a>
                  </li>
                {% endif %}

            </div>
          </div>
        </div>
      </nav>
      <div class="container">
        

        {% block content %}
    
        {% endblock %}
      </div>

  
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% if messages %}
      {% for m in messages %}
        <script>
          Swal.fire({
            "title": "Felicitaciones",
            "text": "{{m}}",
            "icon": "success",
          })
        </script>
      {% endfor %}
    {% endif %}

    {% block js %}
    {% endblock %}
  </body>
<footer class="footer py-3 bg-dark text-white">
  <div class="container">
      <div class="row">
          <div class="col-md-6">
              <p>contacto@endlessride.com</p>
          </div>
          <div class="col-md-6 text-md-end">
              <a href="{% url 'shop:index' %}" class="text-white">Administración</a>
          </div>
      </div>
      <div class="row">
          <div class="col-12 text-center">
              <p class="mb-0">© 2024 EndlessRide. Todos los derechos reservados.</p>
          </div>
      </div>
  </div>
</footer>

</html>

templates/inicio.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
    <nav class="navbar  fixed-top" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand ms-2 text-white" href="{% url "inicio" %}">ENDLESSRIDE</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon text-white"></span>
          </button>
          
          <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel" >
            <div class="offcanvas-header">
              <h5 class="offcanvas-title " id="offcanvasNavbarLabel">ENDLESSRIDE</h5>
              <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body ">
              <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <li class="nav-item">
                  <a class="nav-link active text-white" aria-current="page" href="{% url "inicio" %}">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url "shop:tienda" %}">Tienda</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url "shop:contacto" %}">Contacto</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url "shop:carrito" %}">Carrito</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="#">Mis pedidos</a>
                </li>
                {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link text-white" href="#" onclick="document.getElementById('logout-form').submit(); return false;">Cerrar Sesion</a>
                  </li>
                  <form id="logout-form" method="post" action="{% url 'logout' %}" style="display: none;">
                    {% csrf_token %}
                  </form>
                {% else %}
                  <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'login' %}">Iniciar Sesion</a>
                  </li>
                {% endif %}
                {% if perms.shop.view_producto %}
                  <li class="nav-item">
                    <a href="{% url 'shop:index' %}" class="nav-link text-white">Administración</a>
                  </li>
                {% endif %}


      
            </div>
          </div>
        </div>
      </nav>
    
      <div class="background d-flex align-items-center justify-content-center">
        <div>
            <img class="w-50 mb-5" src="{% static 'img/logo.png' %}" alt="">
            <br>
            <a href="{% url "shop:tienda" %}" class="btn btn-outline-light btn-lg">Tienda</a>

        </div>
    </div>
        {% block content %}
    
        {% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
  </body>
  <footer class="footer py-3 bg-dark text-white">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <p>contacto@endlessride.com</p>
            </div>
            <div class="col-md-6 text-md-end">
                <a href="{% url 'shop:index' %}" class="text-white">Administración</a>
            </div>
        </div>
        <div class="row">
            <div class="col-12 text-center">
                <p class="mb-0">© 2024 EndlessRide. Todos los derechos reservados.</p>
            </div>
        </div>
    </div>
  </footer>
</html>